### ISSUE TITLE
Loading our own image dataset

### ISSUE THREAD

**Issue by aaseagrass** [mdegis/machine-learning#1]
Hello! Currently new in machine learning. I need a svm classifier in order to classify the 2 seagrass species present in our seagrass picture. Can I use this repo for that? Can I build my own dataset using this repo? Thank you! I'm a graduating undergrad ECE student that still fighting for our graduation. Hope anyone can help me.

**Comment by nethajinirmal13** [comment]
you can use this for your classification of seagrass.you should build your own dataset.this repo will not help you in building dataset.
